# GitHub Action para generar un gráfico de contribuciones con una serpiente.

name: Generate Snake

# Configuración de activación automática
on:
  schedule:
    - cron: "0 */6 * * *"  # Ejecuta cada 6 horas
  workflow_dispatch:  # Permite ejecución manual desde Actions

jobs:
  build:
    runs-on: ubuntu-latest

    # Permisos para permitir escritura en el repositorio
    permissions:
      contents: write

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Generar la serpiente
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ecx567
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Mostrar estado del repositorio
        run: git status

      - name: Push de los cambios
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - name: Desplegar en GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

